version = 0.1

[default.deploy.parameters]
stack_name = "lambda-quarkus-native-demo"
resolve_s3 = true
s3_prefix = "lambda-quarkus-native-demo"
region = "sa-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "sa-east-1"
